### ISSUE TITLE
Encryption support?

### ISSUE THREAD

**Issue by skandragon** [mycontroller-org/esphome_api#4]
From what I can tell, the password is supported, but not the encryption layer.  Is this correct?

**Comment by jkandasa** [comment]
@skandragon Yes, you are right. Encryption not added. only password support

**Comment by skandragon** [comment]
Do you think it would be difficult to add?  I've looked at the C code, and it seems like all it does is wrap the protobuf "frames" in an encrypted packet, which consists of a length prefix + encrypted blob.

**Comment by jkandasa** [comment]
@skandragon can you add the c code reference location?

**Comment by skandragon** [comment]
The only reference I have so far is the esphome source itself:  https://github.com/esphome/esphome/tree/dev/esphome/components/api

It's somewhat spread around inside those files, but `api_frame_helper.cpp` seems to have most of it.

**Comment by jkandasa** [comment]
@skandragon ok, I see they are using http://www.noiseprotocol.org
I will check that.

**Comment by jkandasa** [comment]
@skandragon added encryption support via this PR: https://github.com/mycontroller-org/esphome_api/pull/5 and merged into master branch.

**Comment by jkandasa** [comment]
@skandragon I tested the implementation and works ok. I am closing this issue. please reopen if you see an issue on encryption.
